services:
  catalogservice:
    image: ${DOCKER_REGISTRY-}catalogservice
    build:
      context: .
      dockerfile: CatalogService/Dockerfile
    container_name: catalog-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=catalogdb;Database=catalogdb;Username=postgres;Password=postgres
      - Services__OrderServiceUrl=http://host.docker.internal:5004
    ports:
      - "5001:8080"
    depends_on:
      catalogdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - catalog-network
    restart: on-failure


  catalogdb:
    image: postgres
    container_name: catalogdb
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - catalogdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - catalog-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: catalog_pgadmin_container
    restart: always
    ports:
      - "8885:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - catalog-pgadmin-data:/var/lib/pgadmin
    networks:
      - catalog-network

networks:
  catalog-network:
    driver: bridge
    name: catalog-network
    
volumes:
  catalogdb_data:
  catalog-pgadmin-data: 
